name: Android CI

on:
  push:
    branches: [ "master" ]
  pull:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: checkout repo
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew :myExpenses:packageExternReleaseUniversalApk
    - uses: r0adkll/sign-android-release@v1
      name: Sign apk
      id: sign_app
      with:
        releaseDirectory: build/outputs/apk_from_bundle/externRelease
        signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        alias: ${{ secrets.ALIAS }}
        keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
    - uses: actions/upload-artifact@v4
      name: upload signed apk
      with:
        name: app.apk
        path: ${{steps.sign_app.outputs.signedReleaseFile}}
  
