name: Sync fork with upstream
on:
  schedule:
    - cron: "0 0 */1 * *" # Every day
  workflow_dispatch: # Allow manual triggering via Web UI to test.

jobs:
  sync-fork:
    runs-on: ubuntu-latest
    # Needs explicit permission to write to the repository
    permissions:
      contents: write
    steps:
      - uses: thiagokokada/merge-upstream@v1.0.2
        with:
          branch: master
